version: '3.4'

#networks:
#  backend:
#    driver: bridge

services:
  sqlserver:
    build:
      context: ./sqlserver
    container_name: mssql
    environment: 
      MSSQL_SA_PASSWORD: "Pa33wo5d@!" 
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

  familybudget:
    image: ${DOCKER_REGISTRY-}familybudget
    build:
      context: .
      dockerfile: src/FamilyBudget.Web/Dockerfile

   ### PostgreSQL for Keycloak ###########################################
#  postgres-keycloak:
#    image: postgres:14.3-alpine
#    volumes:
#      - keycloak-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=keycloak
#      - POSTGRES_USER=keycloak
#      - POSTGRES_PASSWORD=password
#    networks:
#      - backend

  ### KEYCLOAK
#  keycloak:
#    # image: quay.io/keycloak/keycloak:18.0.0
#    build:
#      context: ./keycloak
#      dockerfile: Dockerfile
#
#    environment:
#      - KC_HEALTH_ENABLED=true
#      - KEYCLOAK_ADMIN=admin 
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/keycloak
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=password
#      - KC_DB=postgres

#    ports:
#      - 8081:8080
#    
#    networks:
#      - backend

volumes:
  db-data:
#  keycloak-data:
